// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBIKvFlUGUqH2JFKbmVwJ_F3iTRRj6vM1o',
    appId: '1:955740652361:web:f02df1b16856cdd23b5098',
    messagingSenderId: '955740652361',
    projectId: 'fireblog-test-1',
    authDomain: 'fireblog-test-1.firebaseapp.com',
    storageBucket: 'fireblog-test-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJOLJR3MxMq4MkGsRJXYzMy7yPOtvBsE0',
    appId: '1:955740652361:android:c24c4e238180f4523b5098',
    messagingSenderId: '955740652361',
    projectId: 'fireblog-test-1',
    storageBucket: 'fireblog-test-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgdCLN32zeRjHJFVCMUPt9VoUN9c7_Nes',
    appId: '1:955740652361:ios:4e5c095a210c9bf83b5098',
    messagingSenderId: '955740652361',
    projectId: 'fireblog-test-1',
    storageBucket: 'fireblog-test-1.appspot.com',
    iosClientId: '955740652361-7cg9vllk0kentuf1uh7kmf5a4g5sqiuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireblogTest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgdCLN32zeRjHJFVCMUPt9VoUN9c7_Nes',
    appId: '1:955740652361:ios:4e5c095a210c9bf83b5098',
    messagingSenderId: '955740652361',
    projectId: 'fireblog-test-1',
    storageBucket: 'fireblog-test-1.appspot.com',
    iosClientId: '955740652361-7cg9vllk0kentuf1uh7kmf5a4g5sqiuu.apps.googleusercontent.com',
    iosBundleId: 'com.example.fireblogTest',
  );
}
